### ISSUE TITLE
feature request: lazy editing

### ISSUE THREAD

**Issue by bling** [terryma/vim-multiple-cursors#61] opened 2013-09-11 19:09 UTC
i think it'd be useful to have an option such that once you're in insert mode that it does *not* update every cursor after each keystroke.  this would solve a bunch of performance problems related to live updates.

basically, how `<C-v>jjjIfoo<Esc>` works.  thanks.

**Comment by balta2ar** [comment] 2015-01-15 14:39
Duplicate of #58.

**Comment by faceleg** [comment] 2015-01-15 19:39
Thanks @balta2ar

**Closed** 2015-01-15 19:39 UTC
Labels: enhancement
