### ISSUE TITLE
Manual cursor/region. Again.

### ISSUE THREAD

**Issue by pocomane** [terryma/vim-multiple-cursors#170] opened 2015-10-22 11:28 UTC
I would like a way to manual place a virtual cursor somewhere or adding region of text to the list of selections. Is there some vim technical limitation about this? Are you interested in implementing this kind of feature? I understand that it could change deeply the plugin logic (ex. you need two phases, one for selection, one for editing), but imho it would be an useful feature, also for the plugin interoperability (ex. one extern plugin can select regions in the weirdest way, than trigger the multiple cursor editing).

I already give a look at vim-multiedit, but, if I am not wrong, it just do not do what I am looking for:
- The cursors should react to the normal-mode command as expected
- The cursors should update real-time
- The regions should behave just like your ctrl-n selections
Sure I could open a feature request also to them, maybe I will do it, but it seems to me that you are closest to the final result (and more active...).

**Comment by balta2ar** [comment] 2015-10-22 13:11
Duplicate of #86.

Development activity here is very low, I have to say. Active contributors are welcome.

**Comment by faceleg** [comment] 2016-01-26 19:00
Closing as duplicate of #86.

**Closed by faceleg** 2016-01-26 19:00 UTC
Labels: feature request, pull request welcome
