### ISSUE TITLE
Getting errors in insert mode

### ISSUE THREAD

**Issue by MaKleSoft** [terryma/vim-multiple-cursors#116] opened 2015-02-09 13:06 UTC
After entering insert mode with multiple cursors (through `c`, `i` or any other command) I get the following error on every keystroke:

```
Error detected while processing function <SNR>53_process_user_input:
line   18:
E488: Trailing characters
-- More -- SPACE/d/j: screen/page/line down, b/u/k: up, q: quit
```

I've tried to disable all other plugins (except vundle) to see if there are any conflicts but the problem is still there. Any idea what this could be caused by?

**Comment by faceleg** [comment] 2015-02-09 19:54
Is #95 relevant?

**Comment by MaKleSoft** [comment] 2015-02-09 21:44
Nope, sorry. Entering insert mode works fine. The errors start to occur when I try to enter characters. It might also be worth noting that the characters are still being inserted (with the error message appearing and disappering almost instantly) except for the keys SPACE, d, j etc. that are mentioned in the error message.

**Comment by eapache** [comment] 2015-02-09 21:53
Can you disable not just all other plugins, but all other non-default settings in your `.vimrc`? I cannot reproduce this so there must be some conflict somewhere.

**Comment by MaKleSoft** [comment] 2015-02-09 22:58
I removed everything from my `.vimrc` except the code for installing the plugin. No change. Here's the content:

```
" set the runtime path to include Vundle and initialize                                                          
set rtp+=~/.vim/bundle/Vundle.vim                                                                                
call vundle#begin()                                                                                              
                                                                                                                 
" let Vundle manage Vundle, required                                                                             
Plugin 'gmarik/Vundle.vim'                                                                                       
                                                                                                                 
Plugin 'terryma/vim-multiple-cursors'                                                                            
                                                                                                                 
call vundle#end()
```

I'm using vim 7.3 on OSX 10.10.2.

**Comment by eapache** [comment] 2015-02-09 23:29
Hmm, the only thing I can think of is that my vim is 7.4. Looking at the list of features in 7.4, it would not surprise me if we unintentionally depend on one of them.

**Comment by MaKleSoft** [comment] 2015-02-09 23:42
Right... just installed 7.4 and it does work now. Probably want to document this somewhere. I wonder why nobody else has noticed this before since OSX ships with 7.3 by default...

**Comment by eapache** [comment] 2015-02-10 00:06
I stuck a note in the readme to that effect. I (personally) have no interesting in trying to make it work with 7.3 or earlier, so I'm going to close this. If anybody else wants to take a crack, feel free to reopen.

**Closed by eapache** 2015-02-10 00:06 UTC

**Comment by faceleg** [comment] 2015-02-10 01:56
Nobody wants to make things work for Vim 7.4.

Surely we'll all be switching to Neovim sometime soon anyway?
