### ISSUE TITLE
Escaping removes original cursor highlight in Gvim

### ISSUE THREAD

**Issue by sourlemon11** [terryma/vim-multiple-cursors#205] opened 2016-07-01 19:09 UTC
In Gvim, I used ESC to leave the multiple cursors mode, which it did. The ruler shows that the cursor was able to move around. However, the cursor was not highlighted in Gvim. I can reset the cursor by refreshing the file (:e). I tested this issue in terminal vim with no problem whatsoever.

**Comment by unclechu** [comment] 2016-07-07 12:55
Duplicate of #201

**Comment by antoinemadec** [comment] 2018-03-21 18:15
Unable to reproduce. Closing issue.

**Closed by antoinemadec** 2018-03-21 18:15 UTC
Labels: bug
