### ISSUE TITLE
Error detected while processing function <SNR>81_process_user_input: line   18: E488: Trailing characters

### ISSUE THREAD

**Issue by obforfair** [terryma/vim-multiple-cursors#187] opened 2016-01-07 09:02 UTC
Error detected while processing function <SNR>81_process_user_input: line   18: E488: Trailing characters

**Comment by faceleg** [comment] 2016-01-25 23:59
Can we have some more information please?

**Comment by faceleg** [comment] 2016-01-26 19:09
Please read https://github.com/terryma/vim-multiple-cursors/blob/master/ISSUES.md and provide more information

**Comment by mattxlee** [comment] 2016-01-27 03:55
Hello, I have the problem too.
I have disabled all other plugins and leave only multiple-cursors, here is the steps for repeat it:
1. press Ctrl+n for many times and selected words
2. press c to remove words and change to insert mode
3. press u then I got the problem

OS: MacOSx 10.11.3
Thanks and Any hints?

**Comment by SukumarMehta** [comment] 2016-02-05 23:24
+1 have this problem too

my setup: basic vim 7.3 via putty

What i do:
1. select multiple instances of a word with ctrl+n
2. 'c' to change mode
3. any keystroke (e.g. 'a') causes an error:
`
Error detected while processing function <SNR>76_process_user_input:
line   18:
E488: Trailing characters
`
4. eventually keystrokes are registered (takes about 5 seconds)

**Comment by carlosbaraza** [comment] 2016-02-29 20:19
:+1:

**Comment by emeve89** [comment] 2016-03-03 13:55
Yes, the same happens to me. Im using vim 7.3 inside tmux.

**Comment by antoinemadec** [comment] 2018-03-21 20:39
Cannot reproduce, closing issue.

**Comment by wchargin** [comment] 2018-11-29 20:15
This absolutely still occurs as of f4fd6ad4e4075dd14d208af059063f1f3cfb7d55.

Steps to reproduce:

  - Disable all plugins other than vim-multiple-cursors:
  - Launch Vim.
  - Enter `hello`.
  - `:set nomodifiable<CR>`
  - With cursor on `hello`, press `<C-N>`.
  - Press `vdd` (or `vcw` or `vihi` or whatever).

Expected behavior: maybe a nice error message like E21.

Actual behavior: E21 appears and then Neovim _completely freezes
forever_ until you force-kill the process. I’ve waited multiple minutes
without pressing keys for this to resolve, and it doesn’t. I’ve also
tried pressing `<Enter>` once in a while, to no avail.

In some cases (maybe with other plugin interaction?) I also receive the message

    Error detected while processing function <SNR>119_wait_for_user_input[10]..<SNR>119_apply_highlight_fix

and then pressing any key will cause the errors to move up or down a
bit, but with no salient change.

I have NVIM v0.2.0 on Debian.

I really like `vim-multiple-cursors`, but this timebomb that can
completely tank a session at any time just because I happen to be in the
wrong buffer when I perform a trivial change is not an acceptable
tradeoff for me.

Could you please reopen this issue?

**Comment by antoinemadec** [comment] 2018-11-29 22:04
@wchargin OK, will reopen the issue.

@balta2ar could you please stop asking people to migrate to a different plugin?
Fixing the issue or, even better, merging the good ideas of other plugins in vim-multiple-cursors would be more productive.
What do you think?

Thanks,
Antoine

**Comment by wchargin** [comment] 2018-11-29 22:18
On the contrary—fixing the underlying issue would be great, but in the
meantime I’m very happy to see @balta2ar’s link. Having a faster and
more stable plugin is much appreciated: now I can have at least _some_
support for multiple cursors, even if it’s not the plugin that I’m used
to. So, thanks!

**Comment by wchargin** [comment] 2018-11-29 22:32
Hi @antoinemadec. I’m very grateful for the value that this plugin has
provided me over the years, and to you and the other contributors for
developing and maintaining it. I don’t mean to diminish that at all!
It’s also great to hear that the plugin is still being actively
maintained.

By “now I can have at least some support for multiple cursors”, I meant
to communicate that unfortunately I can’t use this plugin in its current
state, so I was happy to see that there is an alternative that does
appear to work better for me. If this bug is fixed and this plugin
continues to be a more reliable option, I’d be happy to switch back to
it—I do have the bindings in my muscle memory, after all. :-)

Thanks again.

**Comment by balta2ar** [comment] 2018-11-30 10:01
> I do have the bindings in my muscle memory, after all

@wchargin You don't have to break your habits, the alternative plugin can be configured to have the same shortcuts. There is a wiki that contains a lot of useful information on that: 
https://github.com/mg979/vim-visual-multi/wiki/Q.-Quick-start#c-n-or-c-d-selects-word-under-cursor

> could you please stop asking people to migrate to a different plugin?

@antoinemadec I shared my thoughts with you on the matter on the email specified in your account. I'd appreciate if you read it. Thanks!

**Closed** 2020-07-30 19:51 UTC
Labels: bug, pull request welcome, wontfix
