### ISSUE TITLE
Problem inserting

### ISSUE THREAD

**Issue by gabrielformica** [terryma/vim-multiple-cursors#95] opened 2014-10-28 15:30 UTC
It always give the message "Key 'i' cannot be replayed at #number cursor locations"
with #number equals to the number of cursors.

Same with the key 'a', 'I', 'A'

**Comment by evanrelf** [comment] 2015-01-28 02:10
I also have this problem. Thankfully it works with other keys so I can still use `c` to change words

**Comment by eapache** [comment] 2015-01-28 02:43
I took a quick look at this and didn't find anything obviously wrong with the code. It appears that vim is perfectly OK with being fed `"c\<Plug>(function)"` but not `"i\<Plug>(function)"`. It may be worth asking vim upstream why this discrepancy exists.

In the short term for this plugin, it may be possible to add a manual work-around similar to the one in place for `:` at https://github.com/terryma/vim-multiple-cursors/blob/master/autoload/multiple_cursors.vim#L1081

**Comment by eapache** [comment] 2015-01-28 03:17
On further reflection this isn't a bug at all. Multiple cursors (by default) leaves you in visual mode, not normal mode. Pressing `i`, `a`, etc in visual mode is not possible even in regular vim - those bindings are simply not defined for cursors that cover multiple characters.

If you wish to enter insert mode from the default multiple cursors, you must first press `v` (as documented in the readme) to enter normal mode, and then `i`, `a`, etc work as intended.

If you wish to insert directly from visual mode with multiple cursors, you must first be able to insert directly from visual mode in normal vim. This may be possible with some fancy `:vnoremap` magic, but it isn't in the default configuration, and it seems a bit out of scope for this plugin.

**Closed** 2015-01-28 03:58 UTC
Labels: bug

**Comment by balta2ar** [comment] 2015-01-28 07:18
@eapache Thanks for looking into that! I'm not quite sure this is related, but while you're at it, could you maybe take a look at #102? The problem is reproduced as follows: set `let g:multi_cursor_exit_from_insert_mode = 0`, select N cursors, press `v` to go to Normal mode, press `i` to go to Insert mode, type something, and then press `Esc`. At this moment we should transition from Insert to Normal mode leaving multiple cursors active **and** they should be moved one character back where possible (as in traditional vim). Switch back to Normal mode is happening, though, but I also get `Key '^[' cannot be replayed at 1 cursor location` message and cursors stay where they are.

**Comment by eapache** [comment] 2015-01-28 16:32
The fix for making all cursors move one character back is really simple; @faceleg if you could give me limited access to create branches or something, I don't really feel like cloning this and playing with git remotes right now.

I cannot immediately reproduce the 'replayed' error.

**Comment by faceleg** [comment] 2015-01-28 20:15
@eapache I don't have permission to add contributors, @terryma if you have a chance, could you please add @eapache as a contributor?
