### ISSUE TITLE
Plugin has stopped working

### ISSUE THREAD

**Issue by hallzy** [terryma/vim-multiple-cursors#246] opened 2018-02-25 19:41 UTC
OS = Ubuntu 16.04 LTS

Vim Version:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 02 2017 06:40:50)
Included patches: 1-134
```

The latest version of  the plugin fails to work with my normal vimrc file, and an extremely minimalist vimrc file.

This is the minimalist vimrc file I used to test:

```vim
if has('gui_running')
  " Use the specified location, and suppress the git error.
  silent call plug#begin('~/vim/vimfiles/plugged')
else
  call plug#begin()
endif

Plug 'terryma/vim-multiple-cursors'

call plug#end()

let g:multi_cursor_exit_from_visual_mode=0
let g:multi_cursor_exit_from_insert_mode=0
```
If I start multiple cursors on a word, the second I press `ctrl+n` I get all these errors:

```
Error detected while processing /path/to/vim-multiple-cursors/autoload/multiple_cursors.vim:
line   11:
E697: Missing end of List ']': 
E15: Invalid expression: [ 'g:multi_cursor_next_key',
line   12:
E10: \ should be followed by /, ? or &
line   13:
E10: \ should be followed by /, ? or &
line   14:
E10: \ should be followed by /, ? or &
line   31:
E15: Invalid expression: 
E15: Invalid expression: {
line   32:
E10: \ should be followed by /, ? or &
line   33:
E10: \ should be followed by /, ? or &
line   34:
E10: \ should be followed by /, ? or &
Error detected while processing function 12:
line    9:
E15: Invalid expression: 
E15: Invalid expression: {
line   10:
E10: \ should be followed by /, ? or &
line   11:
E10: \ should be followed by /, ? or &
line   12:
E10: \ should be followed by /, ? or &
line   13:
E10: \ should be followed by /, ? or &
line   14:
E10: \ should be followed by /, ? or &
line   15:
E10: \ should be followed by /, ? or &
Error detected while processing function multiple_cursors#new[13]..29[3]..25:
line    1:
E716: Key not present in Dictionary: saved_settings['virtualedit'] = &virtualedit
line    2:
E716: Key not present in Dictionary: saved_settings['cursorline'] = &cursorline
line    3:
E716: Key not present in Dictionary: saved_settings['lazyredraw'] = &lazyredraw
line    4:
E716: Key not present in Dictionary: saved_settings['paste'] = &paste
line    5:
E716: Key not present in Dictionary: saved_settings['clipboard'] = &clipboard
Error detected while processing function multiple_cursors#new[14]..<SNR>27_wait_for_user_input[1]..<SNR>27_display_error:
line    2:
E10: \ should be followed by /, ? or &
line    3:
E10: \ should be followed by /, ? or &
line   11:
E10: \ should be followed by /, ? or &
line   12:
E10: \ should be followed by /, ? or &
line   13:
E10: \ should be followed by /, ? or &
```

The same output also occurs if I initiate the plugin with a visual selection.

With my normal vimrc file the errors are suppressed for some reason but it still doesn't work. My normal vimrc file is way way too long to post here so I won't, but if I start using multiple cursors with the `ctrl+n` again to select a word, it does that successfully. I can seem to move my cursor fine, but as soon as I try to type any kind of text it fails.

For example, if I use `i` to enter insert mode, it takes a good 5 seconds for my typed text to appear which it has never done previously, and if I try to type a space it doesn't print a space, it prints `<C-R>=AutoPairsSpace()<CR>` to the file. If I press tab, nothing is printed to the file, but the command `=TriggerSnippet()<CR><Plug>(multiple-cursors-apply)<Plug>(multiple-cursors-detect)` is displayed at the bottom of the buffer as a command to enter. If I press enter to enter the command it tells me that `CR` is an undefined variable and that that expression is invalid.

If I press the enter key for a new line (while still in insert mode) it prints `<SNR>77_DiscretionaryEnd<SNR>25_AutoPairsReturn` to the screen, and only the first cursor gets a newline, which was put before that thing it printed.

Unfortunately, I cannot recall what the last version of multi cursors was that I used, but I have never had this problem before and nothing has changed sine then in my vim configuration apart from updating of plugins.

**Comment by balta2ar** [comment] 2018-02-25 19:56
cc @antoinemadec

**Comment by antoinemadec** [comment] 2018-02-25 20:13
Will look at it next week.

**Comment by hallzy** [comment] 2018-03-01 05:26
If it helps at all, I have tracked down the problem commit for me to be 26bf0cec8ba723c2ed938bbb3d67a1654ff9e12a. The commit right before that which is 9d4fee8cdf2fd560c0eabfd8dbe708207796f8e0 works fine for me.

**Comment by antoinemadec** [comment] 2018-03-01 21:28
Hi @hallzy ,

The first error you report (```E15: Invalid expression: [ 'g:multi_cursor_next_key',```) is due to the fact that you are missing ```set nocompatible``` in your minimal .vimrc.
That is why you do not see those errors in your everyday .vimrc.
That "error" is actually due to an unsupported syntax in "compatible mode".
That was already there before my series of commits, for instance in:
  a97dab5bc440bf0a7b62bb2de4479963a888f4ff (master~8)
That is not a bug.

Regarding the 5 seconds of wait when you type ```i```, this is indeed due to:
  9d4fee8cdf2fd560c0eabfd8dbe708207796f8e0 (mastrer~1)
We try to use ```timeoutlen``` like vim before printing a char that starts a mapping in insert mode.
Here are some questions:

1. Would you happen to have something like ```imap ii <Esc>``` in your .vimrc ?
2. Also what is your ```timeoutlen``` value ?
3. What time does it take to type ```i``` in insert mode when not using this plugin ?

That commit allows to have insert mapping with more than 2 letters and mimic the Vim behavior in terms of insert mappings.
There was a slight issue because we were 1.5times slower than ```timeoutlen```, but that will be fixed by #247

**Comment by hallzy** [comment] 2018-03-01 22:25
So I think I found the problem. I don't know why I didn't recognise it earlier, but I will start by answering your 3 questions.

> 1. Would you happen to have something like `imap ii <Esc> in your .vimrc ?

No I do not.

> 2 What is my timeoutlen ?

I don't set that, so it is at the default of 1000. I just set it to 3 which seems to fix the timing issue.

> What time does it take to type "i" in insert mode when not using the plugin?

It is instant.

Now onto what I found... The "AutoPairsSpace" is from the Auto-Pairs plugin. For whatever reason, the commit I referenced in multiple-cursors causes that to be printed out, but before that commit it never did that... Similarly with DiscretionaryEnd which is from the endwise plugin.

I no longer see `=TriggerSnippet()<CR><Plug>(multiple-cursors-apply)<Plug>(multiple-cursors-detect)` at all in my testing...

By the way, this new minimal vimrc file now does have the problem where the autopairs and endwise text is printed to the file (the timing issue is gone) and also sets nocompatible and the timeoutlen:

```vim
call plug#begin()

Plug 'terryma/vim-multiple-cursors'
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-endwise'

call plug#end()

set nocompatible

set timeoutlen=3

let g:multi_cursor_exit_from_visual_mode=0
let g:multi_cursor_exit_from_insert_mode=0
```

It seems as though then that compatibility with some other plugins may have broken. Those are the only 2 plugins I have found a problem with thus far.

**Comment by hallzy** [comment] 2018-03-01 22:35
As an added note, I never set `nocompatible` in my normal vimrc file either but never got the errors. It turns out that if a file called `.gvimrc` or `.vimrc` is loaded when vim starts then `nocompatible` is automatically set.

I got those errors before because I used the minimal vimrc file by doing `vim -u minimal-vimrc` and when you do that `nocompatible` is NOT set automatically.

**Comment by antoinemadec** [comment] 2018-03-01 22:37
26bf0cec8ba723c2ed938bbb3d67a1654ff9e12a removes ```g:multi_cursor_insert_maps``` and directly uses Vim functions to know if there are insert mappings matching the characters you just typed.
It makes the insert mappings work in insert mode with less manual steps and allows 2+ char insert mappings. Which is a nice feature.

Could you please type ```:imap``` and copy paste the result of that command ?
I am pretty sure that the other plugins add insert mappings...

**Comment by hallzy** [comment] 2018-03-01 22:46
You are correct... There are a lot of insert mappings here.. this is everything which includes plugins and some stuff I have to insert some math characters and greek letters etc:

```
i  <BS>        *@<C-R>=AutoPairsDelete()<CR>
i  §           *@<C-R>=AutoPairsMoveCharacter('''')<CR>
i  ¢           *@<C-R>=AutoPairsMoveCharacter('"')<CR>
i  ©           *@<C-R>=AutoPairsMoveCharacter(')')<CR>
i  ¨           *@<C-R>=AutoPairsMoveCharacter('(')<CR>
i  î           *@<Esc>:call AutoPairsJump()<CR>a
i  ð           *@AutoPairsToggle()
i  â           *@<C-R>=AutoPairsBackInsert()<CR>
i  å           *@<C-R>=AutoPairsFastWrap()<CR>
i  ý           *@<C-R>=AutoPairsMoveCharacter('}')<CR>
i  û           *@<C-R>=AutoPairsMoveCharacter('{')<CR>
i  Ý           *@<C-R>=AutoPairsMoveCharacter(']')<CR>
i  Û           *@<C-R>=AutoPairsMoveCharacter('[')<CR>
i  <C-H>       *@<C-R>=AutoPairsDelete()<CR>
i  <CR>        &@<CR><SNR>79_DiscretionaryEnd<SNR>25_AutoPairsReturn
i  <Space>     *@<C-]><C-R>=AutoPairsSpace()<CR>
i  "           *@<C-R>=AutoPairsInsert('"')<CR>
i  '           *@<C-R>=AutoPairsInsert('''')<CR>
i  (           *@<C-R>=AutoPairsInsert('(')<CR>
i  )           *@<C-R>=AutoPairsInsert(')')<CR>
i  [           *@<C-R>=AutoPairsInsert('[')<CR>
i  ]           *@<C-R>=AutoPairsInsert(']')<CR>
i  `           *@<C-R>=AutoPairsInsert('`')<CR>
i  {           *@<C-R>=AutoPairsInsert('{')<CR>
i  }           *@<C-R>=AutoPairsInsert('}')<CR>
i  <Plug>(multiple-cursors-wait) * <C-O>:call <SNR>183_wait_for_user_input('')<CR>
i  <Plug>(multiple-cursors-detect) * <C-O>:call <SNR>183_detect_bad_input()<CR>
i  <Plug>(multiple-cursors-apply) * <C-O>:call <SNR>183_apply_user_input_next('i')<CR>
i  <Plug>(multiple-cursors-input) * <C-O>:call <SNR>183_process_user_input()<CR>
i  <S-Tab>     * <C-R>=BackwardsSnippet()<CR>
i  <Plug>(table-mode-tableize) * |<Esc>:call tablemode#TableizeInsertMode()<CR>a
i  <Plug>ISurround * <C-R>=<SNR>104_insert(1)<CR>
i  <Plug>Isurround * <C-R>=<SNR>104_insert()<CR>
i  <Plug>AlwaysEnd & <SNR>79_AlwaysEnd
i  <Plug>DiscretionaryEnd & <SNR>79_DiscretionaryEnd
i  <SNR>79_AlwaysEnd * <C-R>=<SNR>79_crend(1)<CR>
i  <SNR>79_DiscretionaryEnd * <C-R>=<SNR>79_crend(0)<CR>
i  <Plug>(emmet-anchorize-summary) * <C-R>=emmet#util#closePopup()<CR><C-R>=emmet#anchorizeURL(1)<CR>
i  <Plug>(emmet-anchorize-url) * <C-R>=emmet#util#closePopup()<CR><C-R>=emmet#anchorizeURL(0)<CR>
i  <Plug>(emmet-remove-tag) * <C-R>=emmet#util#closePopup()<CR><C-R>=emmet#removeTag()<CR>
i  <Plug>(emmet-split-join-tag) * <Esc>:call emmet#splitJoinTag()<CR>
i  <Plug>(emmet-toggle-comment) * <C-R>=emmet#util#closePopup()<CR><C-R>=emmet#toggleComment()<CR>
i  <Plug>(emmet-image-size) * <C-R>=emmet#util#closePopup()<CR><C-R>=emmet#imageSize()<CR>
i  <Plug>(emmet-move-prev-item) * <Esc>:call emmet#moveNextPrevItem(1)<CR>
i  <Plug>(emmet-move-next-item) * <Esc>:call emmet#moveNextPrevItem(0)<CR>
i  <Plug>(emmet-move-prev) * <Esc>:call emmet#moveNextPrev(1)<CR>
i  <Plug>(emmet-move-next) * <Esc>:call emmet#moveNextPrev(0)<CR>
i  <Plug>(emmet-balance-tag-outword) * <Esc>:call emmet#balanceTag(-1)<CR>
i  <Plug>(emmet-balance-tag-inward) * <Esc>:call emmet#balanceTag(1)<CR>
i  <Plug>(emmet-update-tag) * <C-R>=emmet#util#closePopup()<CR><C-R>=emmet#updateTag()<CR>
i  <Plug>(emmet-expand-word) * <C-R>=emmet#util#closePopup()<CR><C-R>=emmet#expandAbbr(1,"")<CR>
i  <Plug>(emmet-expand-abbr) * <C-R>=emmet#util#closePopup()<CR><C-R>=emmet#expandAbbr(0,"")<CR>
i  <Plug>AutoPairsReturn & <SNR>25_AutoPairsReturn
i  <SNR>25_AutoPairsReturn * <C-R>=AutoPairsReturn()<CR>
i  <C-C>       * <Esc>
i  <C-G>S        <Plug>ISurround
i  <C-G>s        <Plug>Isurround
i  <Tab>       * <C-R>=TriggerSnippet()<CR>
i  <CR>          <CR><Plug>DiscretionaryEnd
i  <C-R><Tab>  * <C-R>=ShowAvailableSnips()<CR>
i  <C-S>         <Plug>Isurround
i  <C-X><CR>   & <CR><SNR>79_AlwaysEnd
i  <C-Y>A        <Plug>(emmet-anchorize-summary)
i  <C-Y>a        <Plug>(emmet-anchorize-url)
i  <C-Y>k        <Plug>(emmet-remove-tag)
i  <C-Y>j        <Plug>(emmet-split-join-tag)
i  <C-Y>/        <Plug>(emmet-toggle-comment)
i  <C-Y>i        <Plug>(emmet-image-size)
i  <C-Y>N        <Plug>(emmet-move-prev)
i  <C-Y>n        <Plug>(emmet-move-next)
i  <C-Y>D        <Plug>(emmet-balance-tag-outword)
i  <C-Y>d        <Plug>(emmet-balance-tag-inward)
i  <C-Y>u        <Plug>(emmet-update-tag)
i  <C-Y>;        <Plug>(emmet-expand-word)
i  <C-Y>,        <Plug>(emmet-expand-abbr)
i  Alpha''     * Α
i  A''         * <C-K>:A
i  Beta''      * Β
i  Chi''       * Χ
i  Delta''     * Δ
i  Eta''       * Η
i  Epsilon''   * Ε
i  Gamma''     * Γ
i  Iota''      * Ι
i  Kappa''     * Κ
i  Lambda''    * 
i  Mu''        * Μ
i  Nu''        * Ν
i  Omega''     * Ω
i  Omicron''   * Ο
i  O''         * <C-K>:O
i  Psi''       * Ψ
i  Phi''       * Φ
i  Pi''        * Π
i  Rho''       * Ρ
i  Sigma''     * Σ
i  Tau''       * Τ
i  Theta''     * Θ
i  Upsilon''   * Υ
i  U''         * <C-K>:U
i  Xi''        * Ξ
i  Zeta''      * Ζ
i  \ihn          <Esc>:IHN<CR>
i  \is           <Esc>:IHS<CR>:A<CR>
i  \ih           <Esc>:IHS<CR>
i  alpha''     * α
i  a''         * <C-K>:a
i  because''   * ∵
i  beta''      * β
i  chi''       * χ
i  degrees''   * °
i  double_integral'' * ∬
i  delta''     * δ
i  eta''       * η
i  epsilon''   * ε
i  forall''    *
i  gamma''     * γ
i  integer''   * ℤ
i  integral''  * ∫
i  intersect'' * ∩
i  in''        * ∈
i  iota''      * ι
i  join''      * ⋈
i  kappa''     * κ
i  lambda''    * λ
i  mu''        * μ
i  natural''   * ℕ
i  nu''        * ν
i  omega''     * ω
i  omicron''   * ο
i  o''         * <C-K>:o
i  psi''       * ψ
i  phi''       * φ
i  pi''        * À
i  real''      * ℝ
i  rational''  * ℚ
i  rho''       * ρ
i  subset_eq'' * ⊆
i  subset''    * ⊂
i  sigma''     * σ
i  ss'         * <C-K>ss
i  therefore'' * ∴
i  thereexists'' * ∃
i  tau''       * τ
i  theta''     * θ
i  union''     * ∪
i  upsilon''   * υ
i  u''         * <C-K>:u
i  xi''        * ξ
i  zeta''      * ζ
```

**Comment by antoinemadec** [comment] 2018-03-01 23:01
I see the issue, only the first '<>' pair is evaluated in the mapping.
It might be fixable, will try to push another commit to #247 before the end of the day.

Thanks a lot for the feedback :)

**Comment by hallzy** [comment] 2018-03-01 23:03
Thank you for the help :)

**Comment by antoinemadec** [comment] 2018-03-02 00:24
Done: #247 
Your minimal .vimrc and the testcase is now passing :+1: 
Once merged, we can close this issue.

**Closed** 2018-03-02 14:11 UTC
