### ISSUE TITLE
Make <Esc> key more intelligent

### ISSUE THREAD

**Issue by cowboy** [terryma/vim-multiple-cursors#102] opened 2014-12-10 19:59 UTC
What if pressing `<Esc>` once returned you to multiple-cursor normal mode, and pressing it a *second* time returned you to single-cursor normal mode?

Because right now, I don't have Emacs-style `<C-e>` bound to jump to the end of the line, or your magical `<C-j>` which seems like it does more than just move the cursor down one line (does it move it to the beginning of the line too?) so I have to exit from, then re-enter multiple-cursor mode to do any per-multiple-cursor normal vim commands after entering into insert mode.

This is what I currently have to do to emulate your animated gif Example 2 (note that I have my arrow keys bound to what `hjkl` do for insert mode):

1. `vip` select all lines
1. `<C-n>` enter multiple-cursor mode
1. `I` insert at beginning of line
1. `"` add quote
1. `<Esc>` return to single-cursor normal mode
1. `vip` select all lines
1. `<C-n>` enter multiple-cursor mode
1. `A` append to end of line
1. `"` and `,` to add quote and trailing comma
1. `<Esc>` return to single-cursor normal mode
1. `vip` select all lines
1. `<C-n>` enter multiple-cursor mode
1. `j` to move the cursors down one line
1. `I` insert at beginning of line
1. `<BS>` to get all the words on the same line
1. `<Esc>` return to normal mode
1. (the rest are normal vim commands)

What I'd like to do is:

1. `vip` select all lines
1. `<C-n>` enter multiple-cursor mode
1. `I` insert at beginning of line
1. `"` add quote
1. `<Esc>` return to multiple-cursor normal mode
1. `A` append to end of line
1. `"` and `,` to add quote and trailing comma
1. `<Esc>` return to multiple-cursor normal mode
1. `^` move the cursors to the beginning of the line
1. `j` to move the cursors down one line
1. `I` insert at beginning of line
1. `<BS>` to get all the words on the same line
1. `<Esc>` return to multiple-cursor normal mode
1. `<Esc>` return to single-cursor normal mode
1. (the rest are normal vim commands)

**Comment by balta2ar** [comment] 2015-01-15 13:59
@cowboy Looks like `let g:multi_cursor_exit_from_insert_mode = 0` is what you need.

**Comment by eapache** [comment] 2015-01-28 21:49
I cannot reproduce `Key '^[' cannot be replayed at 2 cursor locations`, pressing escape in insert mode with multiple cursors works fine for me...

**Comment by balta2ar** [comment] 2015-01-28 21:57
@eapache I've just tried your patch, it works just fine. As to the error message, sorry, it's my mistake, I had this culprit in my `~/.vimrc`: `nmap <buffer> <ESC>      <Plug>(unite_exit)`. Again, sorry for the false alarm. Much appreciate your contribution!

**Comment by balta2ar** [comment] 2015-01-28 22:04
@eapache One little moment, though: if I press `h` when cursors are at the beginning of the line, I get `Key 'h' cannot be replayed at 7 cursor locations` (same when pressing `l` in the end of the line). vim doesn't complain if it can't move cursors. Maybe this plugin should not too, at least in such cases?

**Comment by eapache** [comment] 2015-01-28 22:05
The warning is useful if you have some cursors at the beginning of the line and some not, since they are now out of sync. It may or may not be worth hiding if *all* the cursors fail, but that's out of scope for this ticket.

**Closed by eapache** 2015-01-28 22:05 UTC
Labels: enhancement, question
