### ISSUE TITLE
dw command not work on first time

### ISSUE THREAD

**Issue by banminkyoz** [terryma/vim-multiple-cursors#236] opened 2018-01-24 10:34 UTC
**OS**
Window 7

**Example:**

`<div>Hello</div>`

After select 2 div word. If i press dw to remove them. it just delete the first character

`<iv>Hello</iv>`

But if i press dw again, i'll work good

`<>Hello</>`

**This is my current config:**

let g:multi_cursor_exit_from_visual_mode = 0
let g:multi_cursor_exit_from_insert_mode = 0
set backspace=indent,eol,start

**I need help**
Btw, as i use window, when i press C-z, i'll minimize my gVim window,
I'v set `nnoremap <c-z> <nop>` but it just work in normal mode, when i in multi cursor editing, press C-z will minimize my gVim.

Thank you all for your efforts, this pluggin is the best.

**Comment by antoinemadec** [comment] 2018-02-16 02:39
@banminkyoz , I was unable to reproduce this issue.
I tried with the following minimal .vimrc:
```vim
set nocompatible
set backspace=indent,eol,start
let g:multi_cursor_exit_from_visual_mode = 0
let g:multi_cursor_exit_from_insert_mode = 0
```

Could you please try with the same .vimrc and an up-to-date version of the plugin ?

**Comment by antoinemadec** [comment] 2018-03-20 23:47
No comment in a month, was not able to reproduce, closing the issue.

**Closed by antoinemadec** 2018-03-20 23:47 UTC
