### ISSUE TITLE
When I installed the plugin, the arrow keys failed!

### ISSUE THREAD

**Issue by aixiaoxiaoyu** [terryma/vim-multiple-cursors#213] opened 2016-12-30 02:30 UTC
Hello!
    I have disabled all other plugins and leave only multiple-cursors. When I press the arrow keys appear, the following problems.
![Uploading image.png…]()

OS:Ubuntu 14.04
vim:7.4

**Comment by louwers** [comment] 2017-01-20 02:43
https://github.com/terryma/vim-multiple-cursors/blob/master/CONTRIBUTING.md

**Comment by antoinemadec** [comment] 2018-03-21 20:48
Not able to reproduce. Closing issue.

**Closed by antoinemadec** 2018-03-21 20:48 UTC
