### ISSUE TITLE
It's slow in neovim, but fast in vim. Does anyone have the same problem?

### ISSUE THREAD

**Issue by iuunhao** [terryma/vim-multiple-cursors#225] opened 2017-08-18 15:18 UTC
It's slow in neovim, but fast in vim. Does anyone have the same problem?

**Comment by DeathRay1977** [comment] 2017-08-20 12:37
Yes!

**Comment by eapache** [comment] 2017-08-20 16:00
It is reasonably fast for me on both by default.

**Comment by tuyenpm9** [comment] 2017-09-17 07:18
vim profile so significant change when has no multiple-cursor:
`506.000  260.000: VimEnter autocommands`

down to 178 when no multiple-cursor.
`421.000  178.000: VimEnter autocommands`

that's a lot of changes in speed.

**Comment by crisidev** [comment] 2017-09-24 17:52
I use neovim and it is pretty slow. I haven't tried with vim.

**Comment by perrupa** [comment] 2017-11-21 17:09
This plugin was unusably slow until I realized I had another plugin writing the buffer with every change (`907th/vim-auto-save`). Rather than bother with setting up a throttle limit, I just disabled that plugin, which made this crazy-fast again.

**Comment by Leandros** [comment] 2018-01-12 14:58
Thanks for the tip, @perrupa. Turns out that YankRing.vim slows down vim-multiple-cursors 😐 
Now is the question, whether this can be fixed, and what the culprit could be?

**Comment by antoinemadec** [comment] 2018-03-22 17:44
@iuunhao @perrupa @Leandros : do you still see any speed issue on neovim ?
If so could you please provide us with the minimal ```.vimrc``` to repoduce ?
Otherwise, I will close the issue.

**Comment by perrupa** [comment] 2018-03-22 17:53
I believe my slowness was caused by another plugin saving files when entering/exiting insert mode. The `Plug_` issue has long since been resolved for me.

Huge thanks for the amazing plugin and all the work to fix these issues! 👍

**Comment by antoinemadec** [comment] 2018-03-22 18:14
Thanks for the feedback! Closing the issue.
Poke me if you want to reopen it.

**Closed by antoinemadec** 2018-03-22 18:14 UTC
