### ISSUE TITLE
Unwanted text is inserted when using A on multiple selections

### ISSUE THREAD

**Issue by smably** [terryma/vim-multiple-cursors#123] opened 2015-02-23 01:51 UTC
After making a few selections, if I press A to append while still in visual mode, the following text is inserted after each selection:
:call <SNR>28_apply_user_input_next('i')

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb 21 2015 18:49:28)
All other plugins are disabled.

**Comment by mbohuslavek** [comment] 2015-03-09 13:54
I've encountered the same issue after pressing A or I. `:call <SNR>34_apply_user_input_next('i')`.
It happens in both Vim 7.4 1-580 and current version of Neovim.

**Comment by joehanchoi** [comment] 2015-03-10 00:52
Seeing this bug as well, reproduced identically to what mbohuslavek mentioned. I'm on 7.4 1-488 Vim.

**Comment by balta2ar** [comment] 2015-03-10 10:22
@smably @mibk @joehanchoi Does this help: https://github.com/terryma/vim-multiple-cursors/issues/95#issuecomment-71774374?

**Comment by smably** [comment] 2015-03-10 13:13
@balta2ar I think this case is a bit different, in that A and I do work properly in visual block mode (which I see as the closest native Vim analogue of multiple selections).

**Comment by aquach** [comment] 2015-03-10 19:12
@balta2ar When I hit `v` before `A`, it works fine, though as @smably said I would expect that `A` and `I` work as well because they work in visual block, which is effectively a one-column multiple cursor.

**Comment by balta2ar** [comment] 2015-03-10 19:30
@smably @aquach Right, I got your point now. Agree, that would be nice to have. Even though I'm not using that combination myself, now I'd love to give it a try. I'm not sure, but maybe we should consider dealing with #111 first as it might be related.

**Comment by aquach** [comment] 2015-03-10 19:48
Sounds good. Here's a little more motivation from playing around with the plugin in the last few minutes:

Let's say I've freshly made a bunch of cursors with `Ctrl-N`. I now need to remember that if I want to `c` or `d`, I can just press that button, but if I want to `i`, `I`, `a`, or `A`, I need to `v` first to head to normal mode. If I'm in the wrong mode, I get an error or garbage text all over my buffer. This is in contrast to visual mode, where I can `c`, `d`, `i`, `I`, `a`, _and_ `A` without thought (though `i` and `a` are no-ops).

Secondly, if I `A` or `I` from visual mode, it drops me at the beginning or end at the selection, but `A` or `I` in multiple-cursor visual mode inserts garbage text, and `A` or `I` in multiple-cursor normal mode jumps me to the beginning or end of the line. Implementing `A` and `I` in multiple-cursor visual mode would also solve this asymmetry.

**Comment by balta2ar** [comment] 2015-03-17 15:17
@faceleg This one looks like a duplicate of #55 (also #60). People happen to stumble on that problem often, probably it should be mentioned in the README that `I` and `A` do not work in Visual mode yet.

**Comment by faceleg** [comment] 2015-03-17 19:36
Duplicate of #55 and #60

**Comment by faceleg** [comment] 2015-03-17 19:37
@balta2ar yeah good idea - do you have an idea for some suitable text to add?

**Closed by faceleg** 2015-03-17 19:36 UTC
Labels: bug

**Comment by balta2ar** [comment] 2015-03-17 20:55
@faceleg Maybe something like this will do (*cursive is old content*, regular is new):

> *Single key command to switch to Insert mode such as c or s from Visual mode or i, a, I, A in Normal mode should work without any issues.* **NOTE:** vim's Visual block mode also supports I and A commands, however they do not work in this plugin's Visual mode at the moment. Stay tuned.

**Comment by aquach** [comment] 2015-03-17 20:58
I think that'd be a great interim solution. I know I almost got turned off of this plugin entirely after seeing that unexpected behavior. How about:

> Single key command to switch to Insert mode such as c or s from Visual mode or i, a, I, A in Normal mode should work without any issues. _NOTE: vim's Visual block mode also supports I and A commands, however they do not work in this plugin's Visual mode at the moment. For now, to use I and A, switch to normal mode by pressing v first. _

Once I got the hang of it of using v before I and A, it was a lot easier.

**Comment by faceleg** [comment] 2015-03-17 21:03
Done thanks team!
